### PR TITLE
Added checks around trick

### PR DESCRIPTION
**Pull request by gilescope**
Added all the std lib checks around trick and the time seems to double for me from 4ns to 8ns for a signed 64.

Keen to get your feedback.

### CODE REVIEW

**Comment by gilescope** [comment]
Hmm, feel a little uncomfortable with how that copy_nonoverlapping is set up when the string isn't big enough. Let me revise that with something less dubious.

**Comment by gilescope** [comment]
Ok, I think this version is sound. It is still copying a little bit of memory that's unknown which I don't have a feel for if that's really bad or just not good? Maybe we can tweak copy_nonoverlapping to only copy the str length.

**Comment by gilescope** [comment]
And in the morning light I see that 16 chars is not long enough for u64, need 20.

**Comment by pickfire** [comment]
Thanks for sending in the pull request but I don't think str parsing is for this repository. Because in this repository it's specific to parsing 16 characters and the input is expected to be 16 characters long.

But if you still want, can submit a version with checks as well but this still targets 16 characters. What I am suggesting in the rust pull request is that this repository could be a reference to test out the performance of a faster str parsing, so that we can easily benchmark it. Note that we may also want to turn off `target-cpu=native` because rust compiler by default is not built for native cpu.

Closing this for now but if you think it should be here then please tell me.

**Comment by gilescope** [comment]
Sorry - I should have realised that you were aiming specifically for 16 digits in this repo. I think maybe the best route forwards is for me to close down the rust radix10 pr and just make a atoi_radix10 specific crate based around trick and meanwhile push forward with the other rust PR that speeds up all radix for smaller numbers.

**Comment by pickfire** [comment]
Yes, that is the best way, don't need to make it a crate can just make a repo to experiment with it. Can also try to benchmark and see if it affects smaller and larger integers.

**Pull request closed without merging**
